common: &common
  encoding: utf8
  reconnect: false
  pool: 5

development:
  <<: *common
  adapter: sqlite3
  host: localhost
  username: root
  password: 
  database: buddhism_development

test:
  <<: *common
  database: buddhism_test

staging:
  <<: *common
  database: buddhism_staging

production:
  <<: *common
  database: buddhism